### ISSUE TITLE
No sirve de nada hacer NULL un parámetro

### ISSUE THREAD

**Issue by evolentini** [lautarovera/cese-tsse-leds#5]
Esta linea

https://github.com/lautarovera/cese-tsse-leds/blob/bddef8727e8fee3ed529693f4b3da401ca4d4e20/src/leds.c#L78

no tiene ningún efecto porque el puntero que estas apuntando a NULL es una copia del puntero original. No te olvides que C siempre para los parámetros por valor y cuando utilizan punteros los mismos se copian. Por eso la asignación del puntero a NULL en la función no tiene ningún efecto en la variable del programa principal.

**Comment by lautarovera** [comment]
Lo tenia corregido y olvide commitearlo, es decir tenia el refactor en local

**Comment by evolentini** [comment]
No te olvides de formalizar la presentación de las correcciones completando de nuevo el formulario de Google.
